camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [8.0, 16.2]
is_site: True
model_name: 'faster_rcnn_inception_v2_coco_2018_01_28'
roi: [0.0, 0.0, 0.6, 1.0]
